packages:
  - "homepage"
allowBuilds:
  '@typerighter/rpc-server': true
minimumReleaseAgeExclude:
  - '@typerighter/rpc-client@0.36.0 || 0.38.0 || 0.39.0 || 0.40.0 || 0.40.1'
  - '@typerighter/rpc-server@0.36.0 || 0.38.0 || 0.39.0 || 0.40.0 || 0.40.1'
  - typerighter@0.36.0 || 0.38.0 || 0.39.0 || 0.40.0 || 0.40.1
