packages:
  - "homepage"
allowBuilds:
  '@typerighter/rpc-server': true
minimumReleaseAgeExclude:
  - '@typerighter/rpc-client@0.30.4 || 0.30.5 || 0.30.6 || 0.30.7'
  - '@typerighter/rpc-server@0.30.4 || 0.30.5 || 0.30.6 || 0.30.7'
  - typerighter@0.30.4 || 0.30.5 || 0.30.6 || 0.30.7
