packages:
  - "homepage"
allowBuilds:
  '@typerighter/rpc-server': true
minimumReleaseAgeExclude:
  - '@typerighter/rpc-client@0.36.0 || 0.38.0'
  - '@typerighter/rpc-server@0.36.0 || 0.38.0'
  - typerighter@0.36.0 || 0.38.0
