---
_type: Research
_label: "NAT Basics"
_icon: icon.globe
status: 'draft'
---

This section introduces:

- The background.
- The motivation of NAT.
- The concept and mechanism of NAT.
- The implications of NAT (then & now).
- Some real world use cases.

This is based on:

- The book [Computer Networking - A Top-Down Approach](https://ebooks.karbust.me/Technology/Computer%20Networking%20A%20Top-Down%20Approach,%208th%20Edition%20by%20James%20F.%20Kurose,%20Keith%20W.%20Ross-Pearson-9780136681557.pdf) by James Kurose.

## Motivation
