This section documents the research needed to inform the decisions for this project.

## Aims of The Project

Broadly speaking, this project aims to allow 2 Internet users talk to each other out of the box. One basic scenario we desire to support:

1. One user uses the CLI to obtain a code.
2. That user sends the code to connect to the other person.
3. The other person uses that code to establish the connection using the CLI tool.

There can be other more advanced use cases and security for example can be another important factor.

## Scope of Project

## Research Roadmap
