This section documents the research needed to inform the decisions for this project.

## Aims of The Project

Broadly speaking, this project aims to allow 2 Internet users talk to each other out of the box. One basic scenario we desire to support:

1. One user uses the CLI to obtain a code.
2. That user sends the code to connect to the other person.
3. The other person uses that code to establish the connection using the CLI tool.

There can be other more advanced use cases and security for example can be another important factor.

## Scope of Project

This is just a short running project - just a PoC out of pure curiosity.

This project only focuses on:

- Research:
  - A reliable NAT traversal technique over various NAT configurations.
  - Security for P2P.
- Deliverable:
  - A CLI allowing users to selectively/securely connect to each other without a self-hosted server between them.
  - Based on this connection, the user can talk to each other via some standard API.

## Research Roadmap
